# PEP 518 requirements (Pip 10+ required)
# Install required packages before building this package.
[build-system]
requires = ["setuptools", "cython", "wheel", "pybind11>=2.6.0", "numpy>=1.18.5"]
build-backend = "setuptools.build_meta"
